### ISSUE TITLE
Is this possible to run on mobile as well?

### ISSUE THREAD

**Issue by peterzhu1992** [pfrankov/obsidian-colored-tags#1]
I see in manifest it is labeled as desktop only which I wonder if it is good for mobile as well. Thanks!

**Comment by peterzhu1992** [comment]
I manually change the manifest to desktop only false and it runs ok on mobile

**Comment by pfrankov** [comment]
Also checked on mobile and it really works! Changed `"isDesktopOnly": false` in 5a21902
Thank you!
