### ISSUE TITLE
Feature Request/Idea: Custom colors for specific tags

### ISSUE THREAD

**Issue by KrazyManJ** [pfrankov/obsidian-colored-tags#12]
Hey,

I know you want to keep this plugin simple but i am missing that one feature that i wanted at first and also it was the reason why i downloaded this plugin, and that's custom color for specific tags.

**My case of usage**: I want to make tag `#recallable` always yellow and all other tags to be colored like this plugin now does, via palette. This is just an example and i want this for multiple tags.

**My suggested solution**: If you don't want to mess with adding setting components inside setting tab, you could just add multiline textbox where each line will be tag and color separated by space, or other character that does not belong into tag and color.

```md
#recallable #FFFF00
#uncompleted #FF0000
#completed #00FF00
...
```

I guess you get that idea.

Other Sub-Ideas:
- Custom coloring sub-tags of parent specified tag color
- Selecting Pre-Defined colors by obsidian ([here is list of CSS vars](https://docs.obsidian.md/Reference/CSS+variables/Foundations/Colors#Extended+colors))
- Settings intuitive UI to make it better for casual users

Anyways thank you for this plugin! ❤️ Hope my solution will be at least considered to add. This would make this plugin a 10x better!

**Comment by pfrankov** [comment]
Hi there!
Thank you for your very polite and clear suggestion!

>  you could just add multiline textbox where each line will be tag and color separated by space, or other character that does not belong into tag and color.

If you want to customize particular tag's color you don't need this plugin.
You can use [CSS Snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets) or probably just https://github.com/Zachatoo/obsidian-css-editor to edit snippets inside Obsidian. Here is a related discussion where you can get selectors for colorizing specific tags https://forum.obsidian.md/t/how-to-show-all-tags-in-color/40113

Thank you again and with you find right solution to improve your productivity ✨
