### ISSUE TITLE
Diversify colors of multi-nested tags more

### ISSUE THREAD

**Issue by cdelst** [pfrankov/obsidian-colored-tags#15]
Hello! I have a tagging system that relies of nested tags, i.e. `tag1/subtag1/subsubtag2/subsubsubtag3` etc.  And this results in unfortunately boring and hard-to-glance coloring (they are all the same under `tag1`, or very similar).

I would love a feature where I would be able to basically ignore a base tag for coloring purposes. I am imagining a list of tags that get ignored as prefixes.  For my use case, I would enter `tag1` as the ignored prefix tag, to get more individuality between buckets.  

Maybe this is more an issue I have with the variance of the tags when they are bucketed like this, as it is not super effective after 3 groups of tags it seems.

Thanks!

Note: 

Here is a reproduction of what I'm talking about.  The colors only really significantly change for the first bucketing
<img width="770" alt="image" src="https://github.com/pfrankov/obsidian-colored-tags/assets/44860108/d4ce6eb5-43aa-4bb4-80be-bbc81d2f1be8">

**Comment by pfrankov** [comment]
Hello! Good point!
I'm thinking about reducing the total number of colors and also mixing in groups. Even 16 is not very distinguishable.
