### ISSUE TITLE
How do I custom set some tags to special color?

### ISSUE THREAD

**Issue by hotoo** [pfrankov/obsidian-colored-tags#17]
I want to set some tag like `#BUG` show red color, can we do it?

**Comment by pfrankov** [comment]
Hi there! If you want to colorize just one tag — try [Colored Tag Wrangler](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler) instead.

**Comment by pfrankov** [comment]
In version 6.0.0 it should work. I'm not sure if it's stable enough, but it's the best I can do without changes to Obsidian itself.
