### ISSUE TITLE
Apply colors in frontmatter?

### ISSUE THREAD

**Issue by jjanvier** [pfrankov/obsidian-colored-tags#19]
Hello there!

I don't know if it comes from my configuration, if it's a bug, or if it's intended, but I don't see the colored tags in the metadata of my notes. 

Is it normal?

![2024-02-09-011218_3840x1080_scrot](https://github.com/pfrankov/obsidian-colored-tags/assets/3691804/118c2067-28ab-4f52-b5df-39fae37c84cf)

**Comment by pfrankov** [comment]
Hello! Yes, that's expected.
As it is written in Limitations in README.md, it's not possible for now because there is no way to distinguish one tag from another.
