### ISSUE TITLE
Theme setting overide plugin?

### ISSUE THREAD

**Issue by guix54** [pfrankov/obsidian-colored-tags#2]
Hello 
no action of plugin in the front matter properties (test with different themes)
picture with default

![Capture d’écran 2023-08-03 161958](https://github.com/pfrankov/obsidian-colored-tags/assets/3319237/32060383-4242-4ff3-8cd4-ab9ce89fe9b1)

**Comment by pfrankov** [comment]
That's interesting. Please provide more steps to reproduce.

**Comment by guix54** [comment]
hello Pavel, nothing special
in sandbox, I create a new note I insert the tags into properties and I insert same tags into content of the note
> in properties your plugin is inactive (I think due to yaml configuration)
> in content your plugin changes color of tags

**Comment by pfrankov** [comment]
Could you please provide some information where Properties comes from. Is it some plugin?

**Comment by guix54** [comment]
Properties is available in Obsidian since 1.4.1.
https://obsidian.md/changelog/2023-07-26-desktop-v1.4.0/

**Comment by pfrankov** [comment]
I see, seems that it's not available in public.
I'll check when the version will be available but your case of some unstyled tags with non-latin symbols should be resolved in the latest version of the plugin.

**Comment by pfrankov** [comment]
@guix54 it's sad, but the structure of tags in Properties doesn't allow them to be simply referenced via CSS selectors. If you substitute classes through a plugin, as is done for non-latin tags, these classes are overwritten after the plugin is executed.

The ideal would be a universal tagging mechanism with uniform classes or data attributes in Obsidian itself.
Unfortunately, for now, tags in Properties won't be styled.
<img width="420" alt="image" src="https://github.com/pfrankov/obsidian-colored-tags/assets/584632/e27f85a8-d72f-41e5-84e4-1feb132a53a6">
