### ISSUE TITLE
Colours are not applying to tags with underscore inside them

### ISSUE THREAD

**Issue by BestCrochet** [pfrankov/obsidian-colored-tags#26]
Hi there, just downloaded the plugin and found it really useful for colour-coding my tags.

I think there may be a bug with the colours not being applied to tags with underscores inside them. 

Pic below for reference:
![image](https://github.com/user-attachments/assets/091bcf08-87ea-4cfe-b979-5a25951d8f7a)

Thanks!

**Comment by pfrankov** [comment]
Hi there!
That's the limitation of the plugin as mentioned in #20
