### ISSUE TITLE
Same color Tags

### ISSUE THREAD

**Issue by bloominburges** [pfrankov/obsidian-colored-tags#28]
Two tags are showing up with same color: I’ve tried to color palette shift, toggle on and off advanced features, etc. — nope. These two tags want to stay same color, and they are right next to each other in my note so it’s causing an issue… Seems arbitrary but i thought this was whole point of the plugin?

<img width="612" alt="image" src="https://github.com/user-attachments/assets/c76b32b8-b794-40c0-a89f-a124445831e2" />

**Comment by pfrankov** [comment]
This is the limitation of physical world where there are only 5-6 distinguishable main colors by human eye. Try to play around with custom palette https://medialab.github.io/iwanthue/ and set more colors — as many as you like. But you must know that it will be harder to distinguish each color.
