### ISSUE TITLE
Setting custom colors?

### ISSUE THREAD

**Issue by Z3DT** [pfrankov/obsidian-colored-tags#3]
The main function that I liked from RieN7's plugin was the ability to set my own colors for the tags. Is that something that is planned for this plugin as well? Is that what "base chroma" on the roadmap means?

Edit: It also had the option to remove the pound symbol (#) when reading in view mode. While not as big of an ask, it'd be awesome if that were possible too.

**Comment by pfrankov** [comment]
Thank you for the feedback!
The main idea of the plugin is simplicity. So, I've added some necessary settings, but that's it.
Sorry if it does not fit for you.
