### ISSUE TITLE
A fast & delay start？

### ISSUE THREAD

**Issue by yoghurtdewdew** [pfrankov/obsidian-colored-tags#4]
I really love this plugin it makes tags perfect displayed.

However, it seemed to delay the start of obsidian. And I have some seconds could not do anything but wait (clicking on something will breakdown obsidian). Is there someway to have a faster start or to delay the loading of the nice plugin?

<img width="230" alt="image" src="https://github.com/pfrankov/obsidian-colored-tags/assets/63794438/c5a80495-9a70-4a95-9c93-a087976b6e1f">

**Comment by pfrankov** [comment]
Thank you for the feedback!
I have some plans in the Roadmap to improve performance.

BTW, how many tags you have in total?

**Comment by yoghurtdewdew** [comment]
Thanks for your reply!

It's hard to count, I rawly counted the first level tags to be 400~500. 😱 I didn't think so much tags I have.

Maybe because I have placed some papers from others in this vault for easy search, and there may have been tags contamination.

**Comment by pfrankov** [comment]
OMG! That's too much 😨
Sure you have the worst performance issues. Probably the best solution for such number of tags will be delaying or Web Workers. I'll try Web Workers first.

**Comment by pfrankov** [comment]
Around 7000 tags before:
<img width="200" alt="image" src="https://github.com/pfrankov/obsidian-colored-tags/assets/584632/ff7a23b5-dea7-4dee-bae5-3ad0f7ad40ec">

And after [2.0.2 release](https://github.com/pfrankov/obsidian-colored-tags/releases/tag/2.0.2):
<img width="178" alt="image" src="https://github.com/pfrankov/obsidian-colored-tags/assets/584632/3a5ba42a-22de-48be-99e2-cf270d6ebd2d">

Also delayed start of the plugin and now it's only 
<img width="163" alt="image" src="https://github.com/pfrankov/obsidian-colored-tags/assets/584632/385c5096-8443-470e-a20e-697f4fbc6ff5">
all the heavy calculations happen after the load.

**Comment by yoghurtdewdew** [comment]
Thanks a lot for your excellent creativity! That's really a great help!
