### ISSUE TITLE
Color Tags pane too

### ISSUE THREAD

**Issue by NomarCub** [pfrankov/obsidian-colored-tags#5]
The Tags pane doesn't have colors yet.
![image](https://github.com/pfrankov/obsidian-colored-tags/assets/5298006/e54b486f-a0c6-4480-95c2-0833940c8e63)

**Comment by pfrankov** [comment]
Thanks, but this a list of the tags with counters. It shouldn't be styled.

**Comment by NomarCub** [comment]
I know it isn't styled, I'm saying it should be.
