### ISSUE TITLE
Fixed colors for specified tags

### ISSUE THREAD

**Issue by NomarCub** [pfrankov/obsidian-colored-tags#6]
I have some tags that I already colored with custom CSS and would like to switch to this.
1. Right now I don't know how to override the plugin with my own CSS for those.
2. It'd be nice if I could choose colors for them in the plugin settings that are not random.

**Comment by pfrankov** [comment]
Thank you for the feedback!
1. You can override the plugin using the same CSS Selectors as here https://github.com/pfrankov/obsidian-colored-tags/blob/45e5c403c050d7768f49782f768fc98afe4f4d52/main.ts#L172
2. If you are not happy with some colors you can make a palette shift in Settings. Customization of each color will make the plugin too complex and this is not fit with the main idea.

**Comment by NomarCub** [comment]
Thanks for the override!
I thought the "main idea" was tag colors. And I think many more people in the community would want this.
I really don't think it would make it too complex, the focus of the plugin is narrow enough as is.
