### ISSUE TITLE
New tags not coloured until page is re-rendered

### ISSUE THREAD

**Issue by redactedscribe** [pfrankov/obsidian-colored-tags#9]
Firstly, thanks for the plugin, it adds a nice touch.

The issue is that when I create a new tag that doesn't already exist, the theme's default colour is given to the tag. `#new #new2 #new3` will all be the theme's colour for tags, _until_ you change document and come back to the original document, at which point all the three new tags have been given individual colours.

**Comment by pfrankov** [comment]
Thank you for the report. Have you tried to press Enter and wait 4 seconds?

**Comment by redactedscribe** [comment]
> Thank you for the report. Have you tried to press Enter and wait 4 seconds?

You are right, they do indeed update after a few seconds. I probably was testing my normal tags which begin with an uppercase letter and didn't see any change (#10), and by the time I tested lowercase characters, I was already switching between documents quickly for testing purposes. Sorry about that!
